// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"
	"io/fs"
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOS creates a new instance of MockOS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOS {
	mock := &MockOS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOS is an autogenerated mock type for the OS type
type MockOS struct {
	mock.Mock
}

type MockOS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOS) EXPECT() *MockOS_Expecter {
	return &MockOS_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function for the type MockOS
func (_mock *MockOS) Copy(writer io.Writer, reader io.Reader) (int64, error) {
	ret := _mock.Called(writer, reader)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer, io.Reader) (int64, error)); ok {
		return returnFunc(writer, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Writer, io.Reader) int64); ok {
		r0 = returnFunc(writer, reader)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(io.Writer, io.Reader) error); ok {
		r1 = returnFunc(writer, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOS_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type MockOS_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - writer io.Writer
//   - reader io.Reader
func (_e *MockOS_Expecter) Copy(writer interface{}, reader interface{}) *MockOS_Copy_Call {
	return &MockOS_Copy_Call{Call: _e.mock.On("Copy", writer, reader)}
}

func (_c *MockOS_Copy_Call) Run(run func(writer io.Writer, reader io.Reader)) *MockOS_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOS_Copy_Call) Return(n int64, err error) *MockOS_Copy_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOS_Copy_Call) RunAndReturn(run func(writer io.Writer, reader io.Reader) (int64, error)) *MockOS_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOS
func (_mock *MockOS) Create(s string) (*os.File, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOS_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOS_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - s string
func (_e *MockOS_Expecter) Create(s interface{}) *MockOS_Create_Call {
	return &MockOS_Create_Call{Call: _e.mock.On("Create", s)}
}

func (_c *MockOS_Create_Call) Run(run func(s string)) *MockOS_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOS_Create_Call) Return(file *os.File, err error) *MockOS_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockOS_Create_Call) RunAndReturn(run func(s string) (*os.File, error)) *MockOS_Create_Call {
	_c.Call.Return(run)
	return _c
}

// IsNotExist provides a mock function for the type MockOS
func (_mock *MockOS) IsNotExist(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsNotExist")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockOS_IsNotExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNotExist'
type MockOS_IsNotExist_Call struct {
	*mock.Call
}

// IsNotExist is a helper method to define mock.On call
//   - err error
func (_e *MockOS_Expecter) IsNotExist(err interface{}) *MockOS_IsNotExist_Call {
	return &MockOS_IsNotExist_Call{Call: _e.mock.On("IsNotExist", err)}
}

func (_c *MockOS_IsNotExist_Call) Run(run func(err error)) *MockOS_IsNotExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOS_IsNotExist_Call) Return(b bool) *MockOS_IsNotExist_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockOS_IsNotExist_Call) RunAndReturn(run func(err error) bool) *MockOS_IsNotExist_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockOS
func (_mock *MockOS) Open(s string) (fs.File, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockOS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - s string
func (_e *MockOS_Expecter) Open(s interface{}) *MockOS_Open_Call {
	return &MockOS_Open_Call{Call: _e.mock.On("Open", s)}
}

func (_c *MockOS_Open_Call) Run(run func(s string)) *MockOS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOS_Open_Call) Return(file fs.File, err error) *MockOS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockOS_Open_Call) RunAndReturn(run func(s string) (fs.File, error)) *MockOS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockOS
func (_mock *MockOS) ReadFile(s string) ([]byte, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOS_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockOS_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - s string
func (_e *MockOS_Expecter) ReadFile(s interface{}) *MockOS_ReadFile_Call {
	return &MockOS_ReadFile_Call{Call: _e.mock.On("ReadFile", s)}
}

func (_c *MockOS_ReadFile_Call) Run(run func(s string)) *MockOS_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOS_ReadFile_Call) Return(bytes []byte, err error) *MockOS_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockOS_ReadFile_Call) RunAndReturn(run func(s string) ([]byte, error)) *MockOS_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockOS
func (_mock *MockOS) Stat(s string) (os.FileInfo, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOS_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockOS_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - s string
func (_e *MockOS_Expecter) Stat(s interface{}) *MockOS_Stat_Call {
	return &MockOS_Stat_Call{Call: _e.mock.On("Stat", s)}
}

func (_c *MockOS_Stat_Call) Run(run func(s string)) *MockOS_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOS_Stat_Call) Return(v os.FileInfo, err error) *MockOS_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockOS_Stat_Call) RunAndReturn(run func(s string) (os.FileInfo, error)) *MockOS_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockOS
func (_mock *MockOS) WriteFile(s string, bytes []byte, fileMode fs.FileMode) error {
	ret := _mock.Called(s, bytes, fileMode)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = returnFunc(s, bytes, fileMode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOS_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockOS_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - s string
//   - bytes []byte
//   - fileMode fs.FileMode
func (_e *MockOS_Expecter) WriteFile(s interface{}, bytes interface{}, fileMode interface{}) *MockOS_WriteFile_Call {
	return &MockOS_WriteFile_Call{Call: _e.mock.On("WriteFile", s, bytes, fileMode)}
}

func (_c *MockOS_WriteFile_Call) Run(run func(s string, bytes []byte, fileMode fs.FileMode)) *MockOS_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOS_WriteFile_Call) Return(err error) *MockOS_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOS_WriteFile_Call) RunAndReturn(run func(s string, bytes []byte, fileMode fs.FileMode) error) *MockOS_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
