// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MedicalDataBloodType.
const (
	A   MedicalDataBloodType = "A+"
	A1  MedicalDataBloodType = "A-"
	AB  MedicalDataBloodType = "AB+"
	AB1 MedicalDataBloodType = "AB-"
	B   MedicalDataBloodType = "B+"
	B1  MedicalDataBloodType = "B-"
	O   MedicalDataBloodType = "O+"
	O1  MedicalDataBloodType = "O-"
)

// Defines values for GetApiV1PersonsParamsSearchField.
const (
	Name       GetApiV1PersonsParamsSearchField = "name"
	Occupation GetApiV1PersonsParamsSearchField = "occupation"
	Surname    GetApiV1PersonsParamsSearchField = "surname"
)

// Backup defines model for Backup.
type Backup struct {
	// CreatedAt The date and time of the backup creation.
	CreatedAt time.Time `json:"createdAt"`

	// Filename The filename of the created database backup.
	Filename string `json:"filename"`

	// Path The full file path of the database backup.
	Path string `json:"path"`

	// SizeBytes Database backup file size in bytes.
	SizeBytes int `json:"sizeBytes"`
}

// DeleteAllResponse defines model for DeleteAllResponse.
type DeleteAllResponse struct {
	DeletedCount *int    `json:"deletedCount,omitempty"`
	Message      *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error     string    `json:"error"`
	Message   string    `json:"message"`
	Status    int       `json:"status"`
	Timestamp time.Time `json:"timestamp"`
}

// MedicalData defines model for MedicalData.
type MedicalData struct {
	// BloodType The blood type of the person.
	BloodType MedicalDataBloodType `json:"bloodType"`

	// Height The height of the person in centimeters.
	Height float32 `json:"height"`

	// MedicalConditions Additional medical information and known conditions.
	MedicalConditions *string `json:"medicalConditions,omitempty"`

	// Weight The weight of the person in kilograms.
	Weight float32 `json:"weight"`
}

// MedicalDataBloodType The blood type of the person.
type MedicalDataBloodType string

// Person Represents a person stored in the population database.
type Person struct {
	// City The city or county where the person lives.
	City string `json:"city"`

	// DateOfBirth The birth date of the person in ISO format (YYYY-MM-DD).
	DateOfBirth openapi_types.Date `json:"dateOfBirth"`

	// Id The identification number of a person.
	Id      int          `json:"id"`
	Medical *MedicalData `json:"medical,omitempty"`

	// Name The full first name of the person.
	Name string `json:"name"`

	// Nationality The person's nationality.
	Nationality string `json:"nationality"`

	// Notes Additional notes about the person.
	Notes *string `json:"notes,omitempty"`

	// Occupation The person's occupation.
	Occupation *string `json:"occupation,omitempty"`

	// Surname The full last name of the person.
	Surname string `json:"surname"`
}

// PersonSummary defines model for PersonSummary.
type PersonSummary struct {
	// Id The identification number of a person.
	Id int `json:"id"`

	// Name The full first name of the person.
	Name string `json:"name"`

	// Surname The full last name of the person.
	Surname string `json:"surname"`
}

// RestoreResponse defines model for RestoreResponse.
type RestoreResponse struct {
	Message string `json:"message"`

	// RestoredFrom The filename of the backup used for restoration.
	RestoredFrom string `json:"restoredFrom"`
}

// PersonId defines model for personId.
type PersonId = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// GetApiV1PersonsParams defines parameters for GetApiV1Persons.
type GetApiV1PersonsParams struct {
	// SearchField Field to filter by
	SearchField *GetApiV1PersonsParamsSearchField `form:"searchField,omitempty" json:"searchField,omitempty"`

	// SearchQuery Partial value to search for
	SearchQuery *string `form:"searchQuery,omitempty" json:"searchQuery,omitempty"`

	// Limit Number of results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetApiV1PersonsParamsSearchField defines parameters for GetApiV1Persons.
type GetApiV1PersonsParamsSearchField string

// PostApiV1PersonsJSONRequestBody defines body for PostApiV1Persons for application/json ContentType.
type PostApiV1PersonsJSONRequestBody = Person

// PutApiV1PersonsIdJSONRequestBody defines body for PutApiV1PersonsId for application/json ContentType.
type PutApiV1PersonsIdJSONRequestBody = Person

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List backups
	// (GET /api/v1/backups)
	GetApiV1Backups(c *gin.Context)
	// Create database backup
	// (POST /api/v1/backups)
	PostApiV1Backups(c *gin.Context)
	// Delete backup by filename
	// (DELETE /api/v1/backups/{filename})
	DeleteApiV1BackupsFilename(c *gin.Context, filename string)
	// Restore database from backup
	// (POST /api/v1/backups/{filename}/restore)
	PostApiV1BackupsFilenameRestore(c *gin.Context, filename string)
	// Delete all persons
	// (DELETE /api/v1/persons)
	DeleteApiV1Persons(c *gin.Context)
	// Get list of persons with optional search and pagination
	// (GET /api/v1/persons)
	GetApiV1Persons(c *gin.Context, params GetApiV1PersonsParams)
	// Create a new person
	// (POST /api/v1/persons)
	PostApiV1Persons(c *gin.Context)
	// Get all person IDs, names and surnames
	// (GET /api/v1/persons/summary)
	GetApiV1PersonsSummary(c *gin.Context)
	// Delete person by ID
	// (DELETE /api/v1/persons/{id})
	DeleteApiV1PersonsId(c *gin.Context, id PersonId)
	// Get person by ID
	// (GET /api/v1/persons/{id})
	GetApiV1PersonsId(c *gin.Context, id PersonId)
	// Update person by ID
	// (PUT /api/v1/persons/{id})
	PutApiV1PersonsId(c *gin.Context, id PersonId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiV1Backups operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Backups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Backups(c)
}

// PostApiV1Backups operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Backups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Backups(c)
}

// DeleteApiV1BackupsFilename operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1BackupsFilename(c *gin.Context) {

	var err error

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameter("simple", false, "filename", c.Param("filename"), &filename)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filename: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1BackupsFilename(c, filename)
}

// PostApiV1BackupsFilenameRestore operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1BackupsFilenameRestore(c *gin.Context) {

	var err error

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameter("simple", false, "filename", c.Param("filename"), &filename)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filename: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1BackupsFilenameRestore(c, filename)
}

// DeleteApiV1Persons operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1Persons(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1Persons(c)
}

// GetApiV1Persons operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Persons(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1PersonsParams

	// ------------- Optional query parameter "searchField" -------------

	err = runtime.BindQueryParameter("form", true, false, "searchField", c.Request.URL.Query(), &params.SearchField)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter searchField: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "searchQuery" -------------

	err = runtime.BindQueryParameter("form", true, false, "searchQuery", c.Request.URL.Query(), &params.SearchQuery)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter searchQuery: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Persons(c, params)
}

// PostApiV1Persons operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Persons(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Persons(c)
}

// GetApiV1PersonsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PersonsSummary(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1PersonsSummary(c)
}

// DeleteApiV1PersonsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1PersonsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PersonId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1PersonsId(c, id)
}

// GetApiV1PersonsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PersonsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PersonId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1PersonsId(c, id)
}

// PutApiV1PersonsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1PersonsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PersonId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiV1PersonsId(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/backups", wrapper.GetApiV1Backups)
	router.POST(options.BaseURL+"/api/v1/backups", wrapper.PostApiV1Backups)
	router.DELETE(options.BaseURL+"/api/v1/backups/:filename", wrapper.DeleteApiV1BackupsFilename)
	router.POST(options.BaseURL+"/api/v1/backups/:filename/restore", wrapper.PostApiV1BackupsFilenameRestore)
	router.DELETE(options.BaseURL+"/api/v1/persons", wrapper.DeleteApiV1Persons)
	router.GET(options.BaseURL+"/api/v1/persons", wrapper.GetApiV1Persons)
	router.POST(options.BaseURL+"/api/v1/persons", wrapper.PostApiV1Persons)
	router.GET(options.BaseURL+"/api/v1/persons/summary", wrapper.GetApiV1PersonsSummary)
	router.DELETE(options.BaseURL+"/api/v1/persons/:id", wrapper.DeleteApiV1PersonsId)
	router.GET(options.BaseURL+"/api/v1/persons/:id", wrapper.GetApiV1PersonsId)
	router.PUT(options.BaseURL+"/api/v1/persons/:id", wrapper.PutApiV1PersonsId)
}

type BadRequestJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type GetApiV1BackupsRequestObject struct {
}

type GetApiV1BackupsResponseObject interface {
	VisitGetApiV1BackupsResponse(w http.ResponseWriter) error
}

type GetApiV1Backups200JSONResponse []Backup

func (response GetApiV1Backups200JSONResponse) VisitGetApiV1BackupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1Backups500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiV1Backups500JSONResponse) VisitGetApiV1BackupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1BackupsRequestObject struct {
}

type PostApiV1BackupsResponseObject interface {
	VisitPostApiV1BackupsResponse(w http.ResponseWriter) error
}

type PostApiV1Backups200JSONResponse Backup

func (response PostApiV1Backups200JSONResponse) VisitPostApiV1BackupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Backups500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostApiV1Backups500JSONResponse) VisitPostApiV1BackupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1BackupsFilenameRequestObject struct {
	Filename string `json:"filename"`
}

type DeleteApiV1BackupsFilenameResponseObject interface {
	VisitDeleteApiV1BackupsFilenameResponse(w http.ResponseWriter) error
}

type DeleteApiV1BackupsFilename204Response struct {
}

func (response DeleteApiV1BackupsFilename204Response) VisitDeleteApiV1BackupsFilenameResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiV1BackupsFilename404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteApiV1BackupsFilename404JSONResponse) VisitDeleteApiV1BackupsFilenameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1BackupsFilenameRestoreRequestObject struct {
	Filename string `json:"filename"`
}

type PostApiV1BackupsFilenameRestoreResponseObject interface {
	VisitPostApiV1BackupsFilenameRestoreResponse(w http.ResponseWriter) error
}

type PostApiV1BackupsFilenameRestore200JSONResponse RestoreResponse

func (response PostApiV1BackupsFilenameRestore200JSONResponse) VisitPostApiV1BackupsFilenameRestoreResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1BackupsFilenameRestore404JSONResponse struct{ NotFoundJSONResponse }

func (response PostApiV1BackupsFilenameRestore404JSONResponse) VisitPostApiV1BackupsFilenameRestoreResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1BackupsFilenameRestore500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostApiV1BackupsFilenameRestore500JSONResponse) VisitPostApiV1BackupsFilenameRestoreResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1PersonsRequestObject struct {
}

type DeleteApiV1PersonsResponseObject interface {
	VisitDeleteApiV1PersonsResponse(w http.ResponseWriter) error
}

type DeleteApiV1Persons200JSONResponse DeleteAllResponse

func (response DeleteApiV1Persons200JSONResponse) VisitDeleteApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1Persons500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteApiV1Persons500JSONResponse) VisitDeleteApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsRequestObject struct {
	Params GetApiV1PersonsParams
}

type GetApiV1PersonsResponseObject interface {
	VisitGetApiV1PersonsResponse(w http.ResponseWriter) error
}

type GetApiV1Persons200JSONResponse []Person

func (response GetApiV1Persons200JSONResponse) VisitGetApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1Persons500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiV1Persons500JSONResponse) VisitGetApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1PersonsRequestObject struct {
	Body *PostApiV1PersonsJSONRequestBody
}

type PostApiV1PersonsResponseObject interface {
	VisitPostApiV1PersonsResponse(w http.ResponseWriter) error
}

type PostApiV1Persons204Response struct {
}

func (response PostApiV1Persons204Response) VisitPostApiV1PersonsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PostApiV1Persons400JSONResponse struct{ BadRequestJSONResponse }

func (response PostApiV1Persons400JSONResponse) VisitPostApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Persons500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostApiV1Persons500JSONResponse) VisitPostApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsSummaryRequestObject struct {
}

type GetApiV1PersonsSummaryResponseObject interface {
	VisitGetApiV1PersonsSummaryResponse(w http.ResponseWriter) error
}

type GetApiV1PersonsSummary200JSONResponse []PersonSummary

func (response GetApiV1PersonsSummary200JSONResponse) VisitGetApiV1PersonsSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsSummary500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiV1PersonsSummary500JSONResponse) VisitGetApiV1PersonsSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1PersonsIdRequestObject struct {
	Id PersonId `json:"id"`
}

type DeleteApiV1PersonsIdResponseObject interface {
	VisitDeleteApiV1PersonsIdResponse(w http.ResponseWriter) error
}

type DeleteApiV1PersonsId204Response struct {
}

func (response DeleteApiV1PersonsId204Response) VisitDeleteApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiV1PersonsId404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteApiV1PersonsId404JSONResponse) VisitDeleteApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsIdRequestObject struct {
	Id PersonId `json:"id"`
}

type GetApiV1PersonsIdResponseObject interface {
	VisitGetApiV1PersonsIdResponse(w http.ResponseWriter) error
}

type GetApiV1PersonsId200JSONResponse Person

func (response GetApiV1PersonsId200JSONResponse) VisitGetApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsId404JSONResponse struct{ NotFoundJSONResponse }

func (response GetApiV1PersonsId404JSONResponse) VisitGetApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsId500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiV1PersonsId500JSONResponse) VisitGetApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutApiV1PersonsIdRequestObject struct {
	Id   PersonId `json:"id"`
	Body *PutApiV1PersonsIdJSONRequestBody
}

type PutApiV1PersonsIdResponseObject interface {
	VisitPutApiV1PersonsIdResponse(w http.ResponseWriter) error
}

type PutApiV1PersonsId204Response struct {
}

func (response PutApiV1PersonsId204Response) VisitPutApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutApiV1PersonsId400JSONResponse struct{ BadRequestJSONResponse }

func (response PutApiV1PersonsId400JSONResponse) VisitPutApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutApiV1PersonsId404JSONResponse struct{ NotFoundJSONResponse }

func (response PutApiV1PersonsId404JSONResponse) VisitPutApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List backups
	// (GET /api/v1/backups)
	GetApiV1Backups(ctx context.Context, request GetApiV1BackupsRequestObject) (GetApiV1BackupsResponseObject, error)
	// Create database backup
	// (POST /api/v1/backups)
	PostApiV1Backups(ctx context.Context, request PostApiV1BackupsRequestObject) (PostApiV1BackupsResponseObject, error)
	// Delete backup by filename
	// (DELETE /api/v1/backups/{filename})
	DeleteApiV1BackupsFilename(ctx context.Context, request DeleteApiV1BackupsFilenameRequestObject) (DeleteApiV1BackupsFilenameResponseObject, error)
	// Restore database from backup
	// (POST /api/v1/backups/{filename}/restore)
	PostApiV1BackupsFilenameRestore(ctx context.Context, request PostApiV1BackupsFilenameRestoreRequestObject) (PostApiV1BackupsFilenameRestoreResponseObject, error)
	// Delete all persons
	// (DELETE /api/v1/persons)
	DeleteApiV1Persons(ctx context.Context, request DeleteApiV1PersonsRequestObject) (DeleteApiV1PersonsResponseObject, error)
	// Get list of persons with optional search and pagination
	// (GET /api/v1/persons)
	GetApiV1Persons(ctx context.Context, request GetApiV1PersonsRequestObject) (GetApiV1PersonsResponseObject, error)
	// Create a new person
	// (POST /api/v1/persons)
	PostApiV1Persons(ctx context.Context, request PostApiV1PersonsRequestObject) (PostApiV1PersonsResponseObject, error)
	// Get all person IDs, names and surnames
	// (GET /api/v1/persons/summary)
	GetApiV1PersonsSummary(ctx context.Context, request GetApiV1PersonsSummaryRequestObject) (GetApiV1PersonsSummaryResponseObject, error)
	// Delete person by ID
	// (DELETE /api/v1/persons/{id})
	DeleteApiV1PersonsId(ctx context.Context, request DeleteApiV1PersonsIdRequestObject) (DeleteApiV1PersonsIdResponseObject, error)
	// Get person by ID
	// (GET /api/v1/persons/{id})
	GetApiV1PersonsId(ctx context.Context, request GetApiV1PersonsIdRequestObject) (GetApiV1PersonsIdResponseObject, error)
	// Update person by ID
	// (PUT /api/v1/persons/{id})
	PutApiV1PersonsId(ctx context.Context, request PutApiV1PersonsIdRequestObject) (PutApiV1PersonsIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetApiV1Backups operation middleware
func (sh *strictHandler) GetApiV1Backups(ctx *gin.Context) {
	var request GetApiV1BackupsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Backups(ctx, request.(GetApiV1BackupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Backups")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiV1BackupsResponseObject); ok {
		if err := validResponse.VisitGetApiV1BackupsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Backups operation middleware
func (sh *strictHandler) PostApiV1Backups(ctx *gin.Context) {
	var request PostApiV1BackupsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Backups(ctx, request.(PostApiV1BackupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Backups")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiV1BackupsResponseObject); ok {
		if err := validResponse.VisitPostApiV1BackupsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1BackupsFilename operation middleware
func (sh *strictHandler) DeleteApiV1BackupsFilename(ctx *gin.Context, filename string) {
	var request DeleteApiV1BackupsFilenameRequestObject

	request.Filename = filename

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1BackupsFilename(ctx, request.(DeleteApiV1BackupsFilenameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1BackupsFilename")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteApiV1BackupsFilenameResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1BackupsFilenameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1BackupsFilenameRestore operation middleware
func (sh *strictHandler) PostApiV1BackupsFilenameRestore(ctx *gin.Context, filename string) {
	var request PostApiV1BackupsFilenameRestoreRequestObject

	request.Filename = filename

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1BackupsFilenameRestore(ctx, request.(PostApiV1BackupsFilenameRestoreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1BackupsFilenameRestore")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiV1BackupsFilenameRestoreResponseObject); ok {
		if err := validResponse.VisitPostApiV1BackupsFilenameRestoreResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1Persons operation middleware
func (sh *strictHandler) DeleteApiV1Persons(ctx *gin.Context) {
	var request DeleteApiV1PersonsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1Persons(ctx, request.(DeleteApiV1PersonsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1Persons")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteApiV1PersonsResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1PersonsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1Persons operation middleware
func (sh *strictHandler) GetApiV1Persons(ctx *gin.Context, params GetApiV1PersonsParams) {
	var request GetApiV1PersonsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Persons(ctx, request.(GetApiV1PersonsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Persons")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiV1PersonsResponseObject); ok {
		if err := validResponse.VisitGetApiV1PersonsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Persons operation middleware
func (sh *strictHandler) PostApiV1Persons(ctx *gin.Context) {
	var request PostApiV1PersonsRequestObject

	var body PostApiV1PersonsJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Persons(ctx, request.(PostApiV1PersonsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Persons")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiV1PersonsResponseObject); ok {
		if err := validResponse.VisitPostApiV1PersonsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1PersonsSummary operation middleware
func (sh *strictHandler) GetApiV1PersonsSummary(ctx *gin.Context) {
	var request GetApiV1PersonsSummaryRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1PersonsSummary(ctx, request.(GetApiV1PersonsSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1PersonsSummary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiV1PersonsSummaryResponseObject); ok {
		if err := validResponse.VisitGetApiV1PersonsSummaryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1PersonsId operation middleware
func (sh *strictHandler) DeleteApiV1PersonsId(ctx *gin.Context, id PersonId) {
	var request DeleteApiV1PersonsIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1PersonsId(ctx, request.(DeleteApiV1PersonsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1PersonsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteApiV1PersonsIdResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1PersonsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1PersonsId operation middleware
func (sh *strictHandler) GetApiV1PersonsId(ctx *gin.Context, id PersonId) {
	var request GetApiV1PersonsIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1PersonsId(ctx, request.(GetApiV1PersonsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1PersonsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiV1PersonsIdResponseObject); ok {
		if err := validResponse.VisitGetApiV1PersonsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiV1PersonsId operation middleware
func (sh *strictHandler) PutApiV1PersonsId(ctx *gin.Context, id PersonId) {
	var request PutApiV1PersonsIdRequestObject

	request.Id = id

	var body PutApiV1PersonsIdJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiV1PersonsId(ctx, request.(PutApiV1PersonsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiV1PersonsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutApiV1PersonsIdResponseObject); ok {
		if err := validResponse.VisitPutApiV1PersonsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xaf28buRH9KgRboC26slayfUn1nxVfDgLOsevkCqQH40DtjiSed8kNybWjGvruxZDc",
	"X1pKllPF138MW0txHt/MvJnh+okmMi+kAGE0nTzRgimWgwHl/gKlpZil+HsKOlG8MFwKOqE39gnhKQjD",
	"Fzxh+DkRZT4HdUIjynFRwcyKRlSwHOiE8pRGVMGXkitI6cSoEiKqkxXkDPc368KuEgaWoOhms8HVupBC",
	"gwUzZektfClBG/wrkcKAsL+yosg8guHvGuE9tfb9s4IFndA/DZuDDt1TPfxRKaluvRFnsnvMmXhgGU+J",
	"coZP6CaiM2FACZZ9BPUAym7xeoB+EfC1gMRASrS1TwC/YoF9kOa9LEX6emhuQctSJUCENGSBtk8orvIb",
	"OK8l92Vhg0nJApThzpuJAmYgvTD92Pq0ApIyA4SJlBieA5ELYlZA5nYvYr/KpcA4g68sLzIMnHE8/mEQ",
	"jwfj80/j8eQ8noxO/00jupAqZ4ZOKO44wN1oVMWaNoqLJVK34Bm4MA2BqZ5WODx2BMnmTFfAungKWZSZ",
	"w5nOf0N08Xh8/tt4fB6PTk/m7D6Ew2ZMGEOZZRYIwTUVkr0Ihvh0oYelBjX8Jjia/wema+M81sV02bXs",
	"oOF6wgWZ43c6YEZvz07HcdTP8rYk/Nr4IarEo4mTNpy7eic5/x0Sg2AvIQMDF1lWR2wv6FK7JH0nS5ca",
	"NbyzcR9aRHPQmi2hs5JeZBlxuqiJ3++kz90mALCbTj1wUClJY8uKj3Wak5mAi4IYV8CXK0PyUhsyBzIH",
	"8wggyGlsU+o0jkmSB/1tmCl1l5k4DlGDiaQNy4uu4ToJf/g0ejsZn0/ODk7CrUgAf+DqfDW4tu1QGFxB",
	"yhOWYXz2OZ5nUqaf7FdCSWYfE9yySjDnaRvKoswR2MXfaUSn+OPC/ry2vw7ww4H9EH9eDxBbw4td1KPb",
	"uSkMxbuwAwNTK8GC6yp0N8HevG3xvMgkw4zJ2VeeI+7xeRzRnAv312njU1eyXSRZ4t5JkXIEEkj6i9Q9",
	"YhnxqwkXziiWfwyueyEfBUnqTbqS9ONXrrEucZbhmkWpvY73uHncw83jDm7ueSaXiuVdo2/O9xFj47sm",
	"ZtQnZisuvc9qgFErpkLh6Bql/jluoVCgsdwSVh1BG6kgxZPYc9WKXcs8nmurjHKzDpOET4hUJEGxW5PH",
	"FSho85Xxhy2Npj9LkUoR8gbm7fViytWu8jTHR65q99wy+3hNnAPIXz9//vx5cHU1uLz8W9f26B9v3g7i",
	"08FotK0XITw8DcMI9qOIiLUzuc6ZsOjbwH6uN2rLzKbqcfcUbqUNafcQATj0QplVGVR5wVza7fS22+4v",
	"mrRWdjefKm64XgV3l8ES38p2u4KwuSzNTvRXUptsTVZM5RloHcxqmSRlwdz+e4/RLOwa+chE+siTFcnZ",
	"PQSp0qV6xhkZO8AXl9g9P1ek7Ejj+5XKbjdZuq6LXL7u1omPZZ4zte4XruMEPB3RUMh/5+D9oz0SovsW",
	"rNju7saCfVXd9CrwWq3LJAGt8RTrYMRXK98rmR82XfiGutSQomx6W4Fc+IaWfoutprnqwOwThl/ESh8Q",
	"iZuZRZkzwZZcLOveGJuBrfHEaQI3Fv1NU95qWi9uZjSiD6C023x0MjqJrW4UIFjB6YSensQnp348sI4a",
	"soIPH0ZDbwI/WoJtHNCd1sAspRP6E5iLgv9rNPXrtm4XxnH8ormZG8j1c0XCD7/NMMCUYuvQJP0z17ah",
	"qYnaRPTcQQoZqKEPQ7cRdgSvlMRtPa9PbdhSo+8vp+QKfQY5nvcOh0+pA7zdSH1U4g7hq8/PtDX648B1",
	"PHre2S23Q3UPUZtoO+aGT1UOb5ops8+kH1BbXL5vj7vNxduvT6H7s9Zs/OwtWp3vdz1vnfVz2JNbTbPk",
	"gyTenUSBKZXwjJ+5L+9nvL6F6tLsDl+J23xNWsf5JqaHXrKsdPvI7d1O4QJtVZUlhj+03GzvKxZK5vap",
	"LiDhCw5p+zoD1Wp/LlT+85b6bgw0ys3+VvSNrIqJRbPj7vRIvj9epm7Xz0DK1qrerpFN5bTcV9dWLw+u",
	"o+W/P0krMhpgh8Wmr3jd1N/iwn6uCWtdHmGBTJhOWIohimGQ2VvFarJGQP0QbInIjbf7Hd3cv1MLORoX",
	"YR33pB5Tnb1stHhr+cS/hLiFQmpupFrbMra3+jec7c3U9xyyFJ2y4JkBRebrKi+/lKDWTWJqYCpZ2eW0",
	"nYvVbVFvOGhNQHeB9qz3noUpe1nywLLSioUziC3XXkT/9B/uVoeeqQ/17KBAl5nxQYn6v8NUxnNuOkZS",
	"WLAyM3QSvuvdNnm9WGgwtn8ssHt0vISNSbs2bC1k7O41Gjx/u/OCBq/K/pyZZIX9sndoorgBxdkRc+cn",
	"MCTbMvvIzYrIwo/13jYqUYf//Qn2TJ/YliX71mwq0/XRFKlivDvKYCncHNLq+BNVb3A649uevucAf7Re",
	"Tx69OWVEwKP34TPu6deloW4uFQ7RxuoO4vXyp7L44jTyFYfDUQcmzJum4JDZpY7s5YQr2V7K9cv98MTT",
	"Q+cD74pZ2i9UodM1S4b1K/vDWn8P/TVaf0/nfE1ml0cp4kdmJ/4uGrXVV5RNXKVgGM/0H9r8Yqi/yC9F",
	"GZL+8sh++b8rG78Uqa0X/l7ymJXif8ksB+slHrQvpt3zXjNW+VTXo4iRra7b92H9Xft93fY/B6Bu5gx7",
	"M8FEAqQOn9a+3QFrc7f5bwAAAP//82goA5skAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
