// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MedicalDataBloodType.
const (
	A   MedicalDataBloodType = "A+"
	A1  MedicalDataBloodType = "A-"
	AB  MedicalDataBloodType = "AB+"
	AB1 MedicalDataBloodType = "AB-"
	B   MedicalDataBloodType = "B+"
	B1  MedicalDataBloodType = "B-"
	O   MedicalDataBloodType = "O+"
	O1  MedicalDataBloodType = "O-"
)

// Backup defines model for Backup.
type Backup struct {
	// CreatedAt The date and time of the backup creation.
	CreatedAt time.Time `json:"createdAt"`

	// Filename The filename of the created database backup.
	Filename string `json:"filename"`

	// Path The full file path of the database backup.
	Path string `json:"path"`

	// SizeBytes Database backup file size in bytes.
	SizeBytes int `json:"sizeBytes"`
}

// DeleteAllResponse defines model for DeleteAllResponse.
type DeleteAllResponse struct {
	DeletedCount *int    `json:"deletedCount,omitempty"`
	Message      *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error     string    `json:"error"`
	Message   string    `json:"message"`
	Status    int       `json:"status"`
	Timestamp time.Time `json:"timestamp"`
}

// MedicalData defines model for MedicalData.
type MedicalData struct {
	// BloodType The blood type of the person.
	BloodType MedicalDataBloodType `json:"bloodType"`

	// Height The height of the person in centimeters.
	Height float32 `json:"height"`

	// MedicalConditions Additional medical information and known conditions.
	MedicalConditions *string `json:"medicalConditions,omitempty"`

	// Weight The weight of the person in kilograms.
	Weight float32 `json:"weight"`
}

// MedicalDataBloodType The blood type of the person.
type MedicalDataBloodType string

// Person Represents a person stored in the population database.
type Person struct {
	// City The city or county where the person lives.
	City string `json:"city"`

	// DateOfBirth The birth date of the person in ISO format (YYYY-MM-DD).
	DateOfBirth openapi_types.Date `json:"dateOfBirth"`

	// Id The identification number of a person.
	Id      int          `json:"id"`
	Medical *MedicalData `json:"medical,omitempty"`

	// Name The full first name of the person.
	Name string `json:"name"`

	// Nationality The person's nationality.
	Nationality string `json:"nationality"`

	// Notes Additional notes about the person.
	Notes *string `json:"notes,omitempty"`

	// Occupation The person's occupation.
	Occupation *string `json:"occupation,omitempty"`

	// Surname The full last name of the person.
	Surname string `json:"surname"`
}

// PersonSummary defines model for PersonSummary.
type PersonSummary struct {
	// Id The identification number of a person.
	Id int `json:"id"`

	// Name The full first name of the person.
	Name string `json:"name"`

	// Surname The full last name of the person.
	Surname string `json:"surname"`
}

// RestoreResponse defines model for RestoreResponse.
type RestoreResponse struct {
	Message string `json:"message"`

	// RestoredFrom The filename of the backup used for restoration.
	RestoredFrom string `json:"restoredFrom"`
}

// PersonId defines model for personId.
type PersonId = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PostApiV1PersonsJSONRequestBody defines body for PostApiV1Persons for application/json ContentType.
type PostApiV1PersonsJSONRequestBody = Person

// PutApiV1PersonsIdJSONRequestBody defines body for PutApiV1PersonsId for application/json ContentType.
type PutApiV1PersonsIdJSONRequestBody = Person

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List backups
	// (GET /api/v1/backups)
	GetApiV1Backups(c *gin.Context)
	// Create database backup
	// (POST /api/v1/backups)
	PostApiV1Backups(c *gin.Context)
	// Delete backup by filename
	// (DELETE /api/v1/backups/{filename})
	DeleteApiV1BackupsFilename(c *gin.Context, filename string)
	// Restore database from backup
	// (POST /api/v1/backups/{filename}/restore)
	PostApiV1BackupsFilenameRestore(c *gin.Context, filename string)
	// Delete all persons
	// (DELETE /api/v1/persons)
	DeleteApiV1Persons(c *gin.Context)
	// Get all persons
	// (GET /api/v1/persons)
	GetApiV1Persons(c *gin.Context)
	// Create a new person
	// (POST /api/v1/persons)
	PostApiV1Persons(c *gin.Context)
	// Get all person IDs, names and surnames
	// (GET /api/v1/persons/summary)
	GetApiV1PersonsSummary(c *gin.Context)
	// Delete person by ID
	// (DELETE /api/v1/persons/{id})
	DeleteApiV1PersonsId(c *gin.Context, id PersonId)
	// Get person by ID
	// (GET /api/v1/persons/{id})
	GetApiV1PersonsId(c *gin.Context, id PersonId)
	// Update person by ID
	// (PUT /api/v1/persons/{id})
	PutApiV1PersonsId(c *gin.Context, id PersonId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiV1Backups operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Backups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Backups(c)
}

// PostApiV1Backups operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Backups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Backups(c)
}

// DeleteApiV1BackupsFilename operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1BackupsFilename(c *gin.Context) {

	var err error

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameter("simple", false, "filename", c.Param("filename"), &filename)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filename: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1BackupsFilename(c, filename)
}

// PostApiV1BackupsFilenameRestore operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1BackupsFilenameRestore(c *gin.Context) {

	var err error

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameter("simple", false, "filename", c.Param("filename"), &filename)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filename: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1BackupsFilenameRestore(c, filename)
}

// DeleteApiV1Persons operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1Persons(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1Persons(c)
}

// GetApiV1Persons operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Persons(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Persons(c)
}

// PostApiV1Persons operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Persons(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Persons(c)
}

// GetApiV1PersonsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PersonsSummary(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1PersonsSummary(c)
}

// DeleteApiV1PersonsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1PersonsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PersonId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1PersonsId(c, id)
}

// GetApiV1PersonsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1PersonsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PersonId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1PersonsId(c, id)
}

// PutApiV1PersonsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1PersonsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PersonId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiV1PersonsId(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/backups", wrapper.GetApiV1Backups)
	router.POST(options.BaseURL+"/api/v1/backups", wrapper.PostApiV1Backups)
	router.DELETE(options.BaseURL+"/api/v1/backups/:filename", wrapper.DeleteApiV1BackupsFilename)
	router.POST(options.BaseURL+"/api/v1/backups/:filename/restore", wrapper.PostApiV1BackupsFilenameRestore)
	router.DELETE(options.BaseURL+"/api/v1/persons", wrapper.DeleteApiV1Persons)
	router.GET(options.BaseURL+"/api/v1/persons", wrapper.GetApiV1Persons)
	router.POST(options.BaseURL+"/api/v1/persons", wrapper.PostApiV1Persons)
	router.GET(options.BaseURL+"/api/v1/persons/summary", wrapper.GetApiV1PersonsSummary)
	router.DELETE(options.BaseURL+"/api/v1/persons/:id", wrapper.DeleteApiV1PersonsId)
	router.GET(options.BaseURL+"/api/v1/persons/:id", wrapper.GetApiV1PersonsId)
	router.PUT(options.BaseURL+"/api/v1/persons/:id", wrapper.PutApiV1PersonsId)
}

type BadRequestJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type GetApiV1BackupsRequestObject struct {
}

type GetApiV1BackupsResponseObject interface {
	VisitGetApiV1BackupsResponse(w http.ResponseWriter) error
}

type GetApiV1Backups200JSONResponse []Backup

func (response GetApiV1Backups200JSONResponse) VisitGetApiV1BackupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1Backups500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiV1Backups500JSONResponse) VisitGetApiV1BackupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1BackupsRequestObject struct {
}

type PostApiV1BackupsResponseObject interface {
	VisitPostApiV1BackupsResponse(w http.ResponseWriter) error
}

type PostApiV1Backups200JSONResponse Backup

func (response PostApiV1Backups200JSONResponse) VisitPostApiV1BackupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Backups500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostApiV1Backups500JSONResponse) VisitPostApiV1BackupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1BackupsFilenameRequestObject struct {
	Filename string `json:"filename"`
}

type DeleteApiV1BackupsFilenameResponseObject interface {
	VisitDeleteApiV1BackupsFilenameResponse(w http.ResponseWriter) error
}

type DeleteApiV1BackupsFilename204Response struct {
}

func (response DeleteApiV1BackupsFilename204Response) VisitDeleteApiV1BackupsFilenameResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiV1BackupsFilename404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteApiV1BackupsFilename404JSONResponse) VisitDeleteApiV1BackupsFilenameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1BackupsFilenameRestoreRequestObject struct {
	Filename string `json:"filename"`
}

type PostApiV1BackupsFilenameRestoreResponseObject interface {
	VisitPostApiV1BackupsFilenameRestoreResponse(w http.ResponseWriter) error
}

type PostApiV1BackupsFilenameRestore200JSONResponse RestoreResponse

func (response PostApiV1BackupsFilenameRestore200JSONResponse) VisitPostApiV1BackupsFilenameRestoreResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1BackupsFilenameRestore404JSONResponse struct{ NotFoundJSONResponse }

func (response PostApiV1BackupsFilenameRestore404JSONResponse) VisitPostApiV1BackupsFilenameRestoreResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1BackupsFilenameRestore500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostApiV1BackupsFilenameRestore500JSONResponse) VisitPostApiV1BackupsFilenameRestoreResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1PersonsRequestObject struct {
}

type DeleteApiV1PersonsResponseObject interface {
	VisitDeleteApiV1PersonsResponse(w http.ResponseWriter) error
}

type DeleteApiV1Persons200JSONResponse DeleteAllResponse

func (response DeleteApiV1Persons200JSONResponse) VisitDeleteApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1Persons500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteApiV1Persons500JSONResponse) VisitDeleteApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsRequestObject struct {
}

type GetApiV1PersonsResponseObject interface {
	VisitGetApiV1PersonsResponse(w http.ResponseWriter) error
}

type GetApiV1Persons200JSONResponse []Person

func (response GetApiV1Persons200JSONResponse) VisitGetApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1Persons500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiV1Persons500JSONResponse) VisitGetApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1PersonsRequestObject struct {
	Body *PostApiV1PersonsJSONRequestBody
}

type PostApiV1PersonsResponseObject interface {
	VisitPostApiV1PersonsResponse(w http.ResponseWriter) error
}

type PostApiV1Persons204Response struct {
}

func (response PostApiV1Persons204Response) VisitPostApiV1PersonsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PostApiV1Persons400JSONResponse struct{ BadRequestJSONResponse }

func (response PostApiV1Persons400JSONResponse) VisitPostApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Persons500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostApiV1Persons500JSONResponse) VisitPostApiV1PersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsSummaryRequestObject struct {
}

type GetApiV1PersonsSummaryResponseObject interface {
	VisitGetApiV1PersonsSummaryResponse(w http.ResponseWriter) error
}

type GetApiV1PersonsSummary200JSONResponse []PersonSummary

func (response GetApiV1PersonsSummary200JSONResponse) VisitGetApiV1PersonsSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsSummary500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiV1PersonsSummary500JSONResponse) VisitGetApiV1PersonsSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApiV1PersonsIdRequestObject struct {
	Id PersonId `json:"id"`
}

type DeleteApiV1PersonsIdResponseObject interface {
	VisitDeleteApiV1PersonsIdResponse(w http.ResponseWriter) error
}

type DeleteApiV1PersonsId204Response struct {
}

func (response DeleteApiV1PersonsId204Response) VisitDeleteApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiV1PersonsId404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteApiV1PersonsId404JSONResponse) VisitDeleteApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsIdRequestObject struct {
	Id PersonId `json:"id"`
}

type GetApiV1PersonsIdResponseObject interface {
	VisitGetApiV1PersonsIdResponse(w http.ResponseWriter) error
}

type GetApiV1PersonsId200JSONResponse Person

func (response GetApiV1PersonsId200JSONResponse) VisitGetApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsId404JSONResponse struct{ NotFoundJSONResponse }

func (response GetApiV1PersonsId404JSONResponse) VisitGetApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1PersonsId500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetApiV1PersonsId500JSONResponse) VisitGetApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutApiV1PersonsIdRequestObject struct {
	Id   PersonId `json:"id"`
	Body *PutApiV1PersonsIdJSONRequestBody
}

type PutApiV1PersonsIdResponseObject interface {
	VisitPutApiV1PersonsIdResponse(w http.ResponseWriter) error
}

type PutApiV1PersonsId204Response struct {
}

func (response PutApiV1PersonsId204Response) VisitPutApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutApiV1PersonsId400JSONResponse struct{ BadRequestJSONResponse }

func (response PutApiV1PersonsId400JSONResponse) VisitPutApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutApiV1PersonsId404JSONResponse struct{ NotFoundJSONResponse }

func (response PutApiV1PersonsId404JSONResponse) VisitPutApiV1PersonsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List backups
	// (GET /api/v1/backups)
	GetApiV1Backups(ctx context.Context, request GetApiV1BackupsRequestObject) (GetApiV1BackupsResponseObject, error)
	// Create database backup
	// (POST /api/v1/backups)
	PostApiV1Backups(ctx context.Context, request PostApiV1BackupsRequestObject) (PostApiV1BackupsResponseObject, error)
	// Delete backup by filename
	// (DELETE /api/v1/backups/{filename})
	DeleteApiV1BackupsFilename(ctx context.Context, request DeleteApiV1BackupsFilenameRequestObject) (DeleteApiV1BackupsFilenameResponseObject, error)
	// Restore database from backup
	// (POST /api/v1/backups/{filename}/restore)
	PostApiV1BackupsFilenameRestore(ctx context.Context, request PostApiV1BackupsFilenameRestoreRequestObject) (PostApiV1BackupsFilenameRestoreResponseObject, error)
	// Delete all persons
	// (DELETE /api/v1/persons)
	DeleteApiV1Persons(ctx context.Context, request DeleteApiV1PersonsRequestObject) (DeleteApiV1PersonsResponseObject, error)
	// Get all persons
	// (GET /api/v1/persons)
	GetApiV1Persons(ctx context.Context, request GetApiV1PersonsRequestObject) (GetApiV1PersonsResponseObject, error)
	// Create a new person
	// (POST /api/v1/persons)
	PostApiV1Persons(ctx context.Context, request PostApiV1PersonsRequestObject) (PostApiV1PersonsResponseObject, error)
	// Get all person IDs, names and surnames
	// (GET /api/v1/persons/summary)
	GetApiV1PersonsSummary(ctx context.Context, request GetApiV1PersonsSummaryRequestObject) (GetApiV1PersonsSummaryResponseObject, error)
	// Delete person by ID
	// (DELETE /api/v1/persons/{id})
	DeleteApiV1PersonsId(ctx context.Context, request DeleteApiV1PersonsIdRequestObject) (DeleteApiV1PersonsIdResponseObject, error)
	// Get person by ID
	// (GET /api/v1/persons/{id})
	GetApiV1PersonsId(ctx context.Context, request GetApiV1PersonsIdRequestObject) (GetApiV1PersonsIdResponseObject, error)
	// Update person by ID
	// (PUT /api/v1/persons/{id})
	PutApiV1PersonsId(ctx context.Context, request PutApiV1PersonsIdRequestObject) (PutApiV1PersonsIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetApiV1Backups operation middleware
func (sh *strictHandler) GetApiV1Backups(ctx *gin.Context) {
	var request GetApiV1BackupsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Backups(ctx, request.(GetApiV1BackupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Backups")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiV1BackupsResponseObject); ok {
		if err := validResponse.VisitGetApiV1BackupsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Backups operation middleware
func (sh *strictHandler) PostApiV1Backups(ctx *gin.Context) {
	var request PostApiV1BackupsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Backups(ctx, request.(PostApiV1BackupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Backups")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiV1BackupsResponseObject); ok {
		if err := validResponse.VisitPostApiV1BackupsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1BackupsFilename operation middleware
func (sh *strictHandler) DeleteApiV1BackupsFilename(ctx *gin.Context, filename string) {
	var request DeleteApiV1BackupsFilenameRequestObject

	request.Filename = filename

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1BackupsFilename(ctx, request.(DeleteApiV1BackupsFilenameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1BackupsFilename")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteApiV1BackupsFilenameResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1BackupsFilenameResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1BackupsFilenameRestore operation middleware
func (sh *strictHandler) PostApiV1BackupsFilenameRestore(ctx *gin.Context, filename string) {
	var request PostApiV1BackupsFilenameRestoreRequestObject

	request.Filename = filename

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1BackupsFilenameRestore(ctx, request.(PostApiV1BackupsFilenameRestoreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1BackupsFilenameRestore")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiV1BackupsFilenameRestoreResponseObject); ok {
		if err := validResponse.VisitPostApiV1BackupsFilenameRestoreResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1Persons operation middleware
func (sh *strictHandler) DeleteApiV1Persons(ctx *gin.Context) {
	var request DeleteApiV1PersonsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1Persons(ctx, request.(DeleteApiV1PersonsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1Persons")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteApiV1PersonsResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1PersonsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1Persons operation middleware
func (sh *strictHandler) GetApiV1Persons(ctx *gin.Context) {
	var request GetApiV1PersonsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Persons(ctx, request.(GetApiV1PersonsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Persons")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiV1PersonsResponseObject); ok {
		if err := validResponse.VisitGetApiV1PersonsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Persons operation middleware
func (sh *strictHandler) PostApiV1Persons(ctx *gin.Context) {
	var request PostApiV1PersonsRequestObject

	var body PostApiV1PersonsJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Persons(ctx, request.(PostApiV1PersonsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Persons")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostApiV1PersonsResponseObject); ok {
		if err := validResponse.VisitPostApiV1PersonsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1PersonsSummary operation middleware
func (sh *strictHandler) GetApiV1PersonsSummary(ctx *gin.Context) {
	var request GetApiV1PersonsSummaryRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1PersonsSummary(ctx, request.(GetApiV1PersonsSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1PersonsSummary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiV1PersonsSummaryResponseObject); ok {
		if err := validResponse.VisitGetApiV1PersonsSummaryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1PersonsId operation middleware
func (sh *strictHandler) DeleteApiV1PersonsId(ctx *gin.Context, id PersonId) {
	var request DeleteApiV1PersonsIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1PersonsId(ctx, request.(DeleteApiV1PersonsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1PersonsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteApiV1PersonsIdResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1PersonsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1PersonsId operation middleware
func (sh *strictHandler) GetApiV1PersonsId(ctx *gin.Context, id PersonId) {
	var request GetApiV1PersonsIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1PersonsId(ctx, request.(GetApiV1PersonsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1PersonsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetApiV1PersonsIdResponseObject); ok {
		if err := validResponse.VisitGetApiV1PersonsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutApiV1PersonsId operation middleware
func (sh *strictHandler) PutApiV1PersonsId(ctx *gin.Context, id PersonId) {
	var request PutApiV1PersonsIdRequestObject

	request.Id = id

	var body PutApiV1PersonsIdJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutApiV1PersonsId(ctx, request.(PutApiV1PersonsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutApiV1PersonsId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutApiV1PersonsIdResponseObject); ok {
		if err := validResponse.VisitPutApiV1PersonsIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZf28buRH9KgRboC26klZSfEn1nxRfDgLOZ8PJFUgPwYHaHUk875J7JNeOaui7F0Ny",
	"f2lpWU6V3P0jSCKXfHwz82aG+0gTmRdSgDCazh5pwRTLwYByv0BpKZYpfk9BJ4oXhktBZ/TGjhCegjB8",
	"zROG/xNR5itQQxpRjpMKZrY0ooLlQGeUpzSiCn4vuYKUzowqIaI62ULOcH2zK+wsYWADiu73e5ytCyk0",
	"WDALlt7C7yVog78SKQwI+5UVReYRjH7TCO+xte5fFazpjP5l1Bx05Eb16HulpLr1m7gtu8dcinuW8ZQo",
	"t/GQ7iO6FAaUYNl7UPeg7BLfDtDPAj4XkBhIibb7E8BHLLCfpHknS5F+OzS3oGWpEiBCGrLGvYcUZ/kF",
	"nNWSu7KwzqRkAcpwZ81EATOQzk3ftz5sgaTMAGEiJYbnQOSamC2QlV2L2Ee5FOhn8JnlRYaOM4kn3w3i",
	"yWBy8WEymV3Es/H0PzSia6lyZuiM4ooDXI1Gla9po7jYIHVrnoFz0xCYarTC4bEjSLZiugLWxVPIoswc",
	"znT1K6KLJ5OLXyeTi3g8Ha7YXQiHjZgwhjLLLBCCcyokRxGMcHStR6UGNfoiOJr/FxY74yzWxXTZ3dlB",
	"w/mEC7LCZzpgxm9eTSdx1I/ytiT80tghqsSj8ZM2nE/1SnL1GyQGwV5CBgbmWVZ7bM/pUjslfStLFxo1",
	"vFeTPrSI5qA120BnJp1nGXG6qIlfb9jnbh8A2A2nHjiolKTZy4qPNZqTmYCJghi3wDdbQ/JSG7ICsgLz",
	"ACDINLYhNY1jkuRBextmSt1lJo5D1GAgacPyortxHYTffRi/mU0uZq9ODsIDTwB/4Op8Nbj23iE3uIKU",
	"JyxD/+xzvMqkTD/YR0JBZocJLlkFmLO0dWVR5ghs/k8a0QV+zO3ntf06wD8H9k/8vB4gtoYXO6lHtzNT",
	"GIo3YQcGhlaCCddl6G6AvX7T4nmdSYYRk7PPPEfck4s4ojkX7te0salL2c6TLHFvpUg5AgkE/Tx1Qywj",
	"fjbhwm2K6R+d607IB0GSepGuJH3/mWvMS5xlOGddaq/jPW4ejnDz8AQ3dzyTG8Xy7qavL44RY/27Jmbc",
	"J+bAL73NaoBRy6dC7ugKpf45bqFQoDHdElYdQRupIMWT2HPVil3LPJ7rII1yswuThCNEKpKg2O3IwxYU",
	"tPnK+P2BRtMfpUilCFkD4/Z6veDqqfS0wiGXtXtmWb6/Js4A5O8fP378OLi6Glxe/qO79/hfr98M4ulg",
	"PD7UixAenoZhBOtRRMTakVzHTFj0rWM/Vxu1ZWZf1bhHErfShrRriAAcOldmWwZVXjAXdk9a2y33N01a",
	"M7uLLxQ3XG+Dq8tgim9Fu51B2EqW5kn0V1KbbEe2TOUZaB2MapkkZcHc+keP0UzsbvKeifSBJ1uSszsI",
	"UqVL9YwxMnaCLS6xen4uSdmWxtcr1b7dYOmaLnLx+rROvC/znKldP3Gdx+HpmIZc/is77x9tkRDdt2DF",
	"9ulqLFhX1UWvAq/VukwS0BpPsQt6fDXznZL5ad2FL6hLDSnKpt8rEAtfUNIfsNUUVx2YfcLwQcz0AZG4",
	"WVqUORNsw8Wmro2xGDhoT5wmcGPR3zTpraZ1frOkEb0Hpd3i4+F4GFvdKECwgtMZnQ7j4dS3B9ZQI1bw",
	"0f145LfAvzZgCwc0p91gmdIZ/QHMvOD/Hi/8vIPbhUkcv6hv5gZy/VyS8M1v0wwwpdgu1En/yLUtaGqi",
	"9hG9cJBCG9TQR6HbCNuCV0rill7VpzZso9H2lwtyhTaDHM/7CZtPqQO83Uh9VuJO4avPz6LV+mPDdT56",
	"3tolD131CFH76NDnRo9VDO+bLrPPpG9QW1y+a7e7zcXbL4+h+7NWb/zsLVod75961nrVj2FPbtXNkp8k",
	"8eYkCkyphGf8lXv4OOP1LVSXZnf4StxWO9I6zhcxPfKSZaXbe27vdgonaKuqLDH8vmVme1+xVjK3o7qA",
	"hK85pO3rDFSr47FQ2c/v1DdjoFBu1reib2SVTCyaJ+5Oz2T780XqYf4MhGyt6u0c2WROy311bfVy5zpb",
	"/PuTtDyjAXaab/qM1w39Ay7s/5qw1uURJsiE6YSl6KLoBpm9Vaw6awTUd8GWiNz4fb+imft3aiFD4yTM",
	"457Uc6qzl40Wby2b+JcQt1BIzY1UO5vGjmb/M3F2Uvb3rf8Lsr8/4jkJ/AHMi9h7pgho82dfiSxkujub",
	"u1WMdetU1Ln9KXnMn6i6nu/U5keS2gk8t949nb3yYETAg7fPM+bpi85INx3jKY5fNZjfzv+rHV8cBl5O",
	"OHzFeCDLSx3ZztPpsW8Z9cvt8MjTU4s/b4pl2q8XQqdrpozq97Gn1XUe+reo6zydqx1ZXp5Foc/MTvxV",
	"NKpL97uy8asUDOOZ/kMrG3T1F9mlKEPSX57ZLn+6tPFzkdp84S+dzpkp/p/IcrBeYkH71tGNH57xurKp",
	"rutMI1tFge8z+qvuo+fe/KJu5owjYUwkQGr3aa3brZ73n/b/CwAA//+NwPYdeCIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
